version: "3.5"

networks:
  froots:
#    external: true
    driver: bridge
    name: froots


services:
  nginx:
    image: nginx:latest
    container_name: froots.nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    networks:
      - froots

  php-fpm:
    image: 339713191041.dkr.ecr.eu-north-1.amazonaws.com/php:latest
#    user: ${MY_UID}:${MY_GID}
    container_name: froots.php
    environment:
      - PHP_FPM_ENABLE=1
      - PHP_FPM_SERVER_ADDR=php
      - PHP_FPM_SERVER_PORT=9000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    links:
      - mysql
      - nginx
    depends_on:
      - mysql
    networks:
      - froots


  mysql:
    container_name: froots.mysql
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - '3307:3306'
    expose:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - froots

volumes:
  mysql_data:
