name: Deploy

on:
  push:
    branches:
      - main
#on:
#  workflow_run:
#    workflows: ["Push the Docker image to AWS ECR Repo"]
#    types:
#      - completed
env:
  AWS_REGION: eu-north-1                   # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: php           # set this to your Amazon ECR repository name
  ECS_SERVICE: deploy-cluster-service                 # set this to your Amazon ECS service name
  ECS_CLUSTER: deploy-cluster                 # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION: ./task-definition.json # set this to the path to your Amazon ECS task definition
  # file, e.g. .aws/task-definition.json
  CONTAINER_NAME: app           # set this to the name of the container in the
  # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: AWS SSM Send-Command
      uses: peterkimzz/aws-ssm-send-command@v1.1.1
      with:
        # AWS access key id
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        # AWS secret access key
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        # Where EC2 instance is
        aws-region: eu-north-1
        # AWS EC2 Instance id or ids
        instance-ids: "i-0d65a546495560c08"
        # Command execution location
        # !!! The line below may vary depending on where your docker-compose file is located.
        working-directory: /var/www/html
        # Bash commands you want to execute
        command: |
          sudo docker-compose stop
          sudo docker-compose rm -f
          sudo docker-compose pull
          sudo docker-compose up -d
          sudo docker image prune -af
        # Comment for Send-Command
        comment: docker-compose.yml file re-pulls newer versions of book-portal images and runs them on the instance.




